// Code generated by proto. DO NOT EDIT.

package main

import (
	"github.com/gin-gonic/gin"

	"activecounter/internal/service"
)

type CmdFun struct {
	Func   func(ctx *gin.Context, req interface{}) (interface{}, error)
	Path   string
	Method string
}

var CmdFunMap = []*CmdFun{
	{Func: service.SayHello, Path: "/v1/SayHello", Method: "GET"},
	{Func: service.SayHelloV2, Path: "/v2/SayHelloV2", Method: "GET"},
}
