// Code generated by proto. DO NOT EDIT.

package main

import (
	"activecounter/internal/service"
)

type ServerCmdMap struct {
	Path    string
	Method  string
	Handler interface{}
}

var CmdFunMap = []ServerCmdMap{
	{Path: "/v1/SayHello", Method: "GET", Handler: service.SayHello},
	{Path: "/v2/SayHelloV2", Method: "GET", Handler: service.SayHelloV2},
}
